### ISSUE TITLE
Within a `change_and_push` are uncommitted writes readable?

### ISSUE THREAD

**Issue by reynir** [robur-coop/git-kv#1]
I observed some behavior which makes me suspect it's not the case. I don't quite understand the code, but I think it might be the case.

The question is:

Can I expect this assertion to hold?

```OCaml
Fs.change_and_push fs @@ fun fs ->
let* () = Fs.set fs Key.(v "hello") "Hello, World!" in
let* hello = Fs.get fs Key.(v "hello") in
assert (hello = "Hello, World!");
Lwt.return_ok ()
```

**Comment by hannesm** [comment]
I suspect the read in the batch is not what you expect above, but @dinosaure will know for sure.

**Comment by dinosaure** [comment]
I think the assertion is false, `change_and_push` executes a closure and you can to multiple `get`/`set`. The goal is to include all `set` into one commit but `set` does not change the internal `HEAD` of `t`: we update the `HEAD` of the local store only at the end of `change_and_push`.

For instance, this code is true:
```ocaml
Fs.change_and_push fs begin fun fs ->
let* () = Fs.set fs Key.(v "hello") "Hello, World!" in
Lwt.return_ok () end >>? fun () ->
let* hello = Fs.get fs Key.(v "hello") in
assert (hello = "Hello, World!");
```

Moreover, it's even true **remotely** because we pushed everything at the end of `change_and_push`.

**Comment by hannesm** [comment]
addressed in https://git.robur.coop/robur/git-kv/pulls/2
