### ISSUE TITLE
change_and_push: changes outside C&P unobservable

### ISSUE THREAD

**Issue by reynir** [robur-coop/git-kv#2]
I notice we do the following:
https://github.com/robur-coop/git-kv/blob/492f57f850e2ef6ac270a269055f95ee51856a85/src/git_kv.ml#L686-L687

This means we create a copy of the record, so changes outside of `change_and_push` that update `t.head` are not observable because it is a copy. This makes the semantics even more complex IMO.

**Comment by hannesm** [comment]
But that's intentional, no? only once the change_and_push is done, the change is observable for everyone.

What I have in mind about change_and_push is that it is atomic -- from the outside you observe only everything before or everything after the change.

From within change_and_push, you should read and write the changed values.

**Comment by reynir** [comment]
Sorry, I think it is slightly different. Let me try to explain:

Task A does `change_and_push fs task_a`.

Meanwhile, task B does `set fs Key.(v "/bar") "hello world!"`.

After that in `task_a` the changes to `/bar` are not observable because the `t.head` is not updated on the `t` inside `task_a`.

Once `task_a` finishes I believe the changes to `/bar` are lost.

**Comment by hannesm** [comment]
addressed in https://git.robur.coop/robur/git-kv/pulls/2 (as test case, and semantics are modified there)

**Comment by reynir** [comment]
So it is still the case that "outside" changes are unobservable, but the `change_and_push` will be "rolled back" in that case.
